### ISSUE TITLE
Not able to use nodejs API's in hono

### ISSUE THREAD

**Issue by devsargam** [code100x/bounty-hook#2]
For interacting with google sheet api.
I am using googleapis package api which uses http2 internally
which is not supported by cloudflare functions.

**Comment by devsargam** [comment]
2 things can be done
- Either use node as a runtime
or
- Somehow figure out the actual post request being sent

**Comment by devsargam** [comment]
@hkirat thoughts?

**Comment by SujithThirumalaisamy** [comment]
> @hkirat thoughts?

I already have that working. But have some questions with it.

**Comment by hkirat** [comment]
oof. 
can we dump somewhere else?
Like some other sheet? Notion?

**Comment by hkirat** [comment]
Whats ur question @SujithThirumalaisamy ?

**Comment by devsargam** [comment]
Yeah notion looks promising

**Comment by SujithThirumalaisamy** [comment]
> Whats ur question @SujithThirumalaisamy ?

It was just a api call. I made it working in the vanila worker as well. But the only  thing is we need to generate a refresh oauth token and add it to the env when deploying. It is working so. Is'nt it optimal. Or we can use a service account based authentication. Because the native google sheets api access with the API_KEY will not provide full functionality in the api.

**Comment by SujithThirumalaisamy** [comment]
```typescript
export default {
	async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
		if (request.method !== 'POST') {
			return new Response('Only POST requests are supported!', { status: 405 });
		}

		const bounty: { name: string; pr: string; amount: string; isDispensed: boolean } = await request.json();
		const requestOptions = {
			method: 'POST',
			redirect: 'follow',
		};

		const res = await fetch(
			`https://oauth2.googleapis.com/token?client_id=${env.CLIENT_ID}&client_secret=${env.CLIENT_SECRET}&refresh_token=${env.REFRESH_TOKEN}&grant_type=refresh_token`,
			requestOptions
		);
		const access_token = await res.json();
		const dataToWrite = JSON.stringify({
			range: 'Sheet1!A1:E1',
			majorDimension: 'ROWS',
			values: [[bounty.name, bounty.pr, bounty.amount, bounty.isDispensed || false]],
		});
		const myHeaders = new Headers({
			'Content-Type': 'application/json',
			Authorization: `Bearer ${access_token.access_token}`,
		});
		const sheetData = {
			method: 'POST',
			headers: myHeaders,
			body: dataToWrite,
			redirect: 'follow',
		};
		try {
			const done = await fetch(
				`https://sheets.googleapis.com/v4/spreadsheets/${env.SPEADSHEET_URL}/values/Sheet1!A1:E1:append?valueInputOption=RAW`,
				sheetData
			);
		} catch (e) {
			// Handle error if necessary
		}

		return new Response('Data successfully written to Google Sheets!');
	},
};

```

**Comment by hkirat** [comment]
If notion is easier lets just go with notion

**Comment by SujithThirumalaisamy** [comment]
> If notion is easier lets just go with notion

That should also use the http2 api underthe hood. Sargam is trying to do that. I am looking if it possible to authenticate with the api using a service account

**Comment by hkirat** [comment]
Notion is good enuf for now
