### ISSUE TITLE
Node APIs not supporting twitter SDK

### ISSUE THREAD

**Issue by shrutsureja** [code100x/bounty-hook#7]
### Problem
I tried using the [twitter-api-v2](https://www.npmjs.com/package/twitter-api-v2) package for this and tried a bunch of different things but in the end Cloudflare Workers don't support the Node APIs.

### Tried Approach
followed the [official doc by cloudflare](https://developers.cloudflare.com/workers/runtime-apis/nodejs/) but still some modules are not supporting.

- [official doc of cloudflare](https://developers.cloudflare.com/workers/runtime-apis/nodejs/eventemitter/) has the `node:events` support but i can't figure out the reason why it is not working 

Here is the screen shot of the errors and modules
![image](https://github.com/code100x/bounty-hook/assets/92169549/15d01d46-4ac5-457f-80ea-ae5293a0c7d9)
![image](https://github.com/code100x/bounty-hook/assets/92169549/75c329c8-6490-4a3c-af0f-2baa50ee5670)

## Possible Solution 

1. Try using the REST api from the official twitter docs (HARD : Because their documentation sucks, non of the example links are working)
2.  dump cloudlflare workers and try something else with node runtime

PS: I have starting working on the REST part, if it works then i will create a PR.

**Comment by shrutsureja** [comment]
I have started on with REST API now !!

**Comment by piyushhsainii** [comment]
> I have started on with REST API now !!

(HARD : Because their documentation sucks, non of the example links are working)

i also tried their documentation, its kinda bad , github links werent working and couldnt set it up. code was there but it's not working.

**Comment by shrutsureja** [comment]
Solved it using the REST APIs making a PR soon
